apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: xdudakm-wac-ambulance-webapi-mongodb-init
    files:
      - params/init-db.js
  - name: xdudakm-wac-ambulance-webapi-config
    literals:
      - database=xdudakm-wac-ambulance
      - collection=ambulance
patches:
  - path: patches/webapi.deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: xdudakm-wac-ambulance-webapi