kind: Service
apiVersion: v1
metadata:
  name: xdudakm-ambulance-webapi
spec:
  selector:
    pod: xdudakm-ambulance-webapi-label
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: webapi-port